#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tailorMS")]
	public partial class tailorMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertuserEnter(userEnter instance);
    partial void UpdateuserEnter(userEnter instance);
    partial void DeleteuserEnter(userEnter instance);
    #endregion
		
		public tailorMSDataContext() : 
				base(global::TMS.Properties.Settings.Default.tailorMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public tailorMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tailorMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tailorMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tailorMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<loginnn> loginnns
		{
			get
			{
				return this.GetTable<loginnn>();
			}
		}
		
		public System.Data.Linq.Table<userEnter> userEnters
		{
			get
			{
				return this.GetTable<userEnter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginnn")]
	public partial class loginnn
	{
		
		private string _username;
		
		private string _pass;
		
		public loginnn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this._pass = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userEnter")]
	public partial class userEnter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _phone;
		
		private string _FullName;
		
		private string _Address_User;
		
		private System.Nullable<double> _collar;
		
		private System.Nullable<double> _chest;
		
		private System.Nullable<double> _waist;
		
		private System.Nullable<double> _hip;
		
		private System.Nullable<double> _arm;
		
		private System.Nullable<double> _sleeves;
		
		private System.Nullable<double> _back;
		
		private System.Nullable<double> _cuffs;
		
		private System.Nullable<double> _lengths;
		
		private System.Nullable<double> _yore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnphoneChanging(long value);
    partial void OnphoneChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnAddress_UserChanging(string value);
    partial void OnAddress_UserChanged();
    partial void OncollarChanging(System.Nullable<double> value);
    partial void OncollarChanged();
    partial void OnchestChanging(System.Nullable<double> value);
    partial void OnchestChanged();
    partial void OnwaistChanging(System.Nullable<double> value);
    partial void OnwaistChanged();
    partial void OnhipChanging(System.Nullable<double> value);
    partial void OnhipChanged();
    partial void OnarmChanging(System.Nullable<double> value);
    partial void OnarmChanged();
    partial void OnsleevesChanging(System.Nullable<double> value);
    partial void OnsleevesChanged();
    partial void OnbackChanging(System.Nullable<double> value);
    partial void OnbackChanged();
    partial void OncuffsChanging(System.Nullable<double> value);
    partial void OncuffsChanged();
    partial void OnlengthsChanging(System.Nullable<double> value);
    partial void OnlengthsChanged();
    partial void OnyoreChanging(System.Nullable<double> value);
    partial void OnyoreChanged();
    #endregion
		
		public userEnter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_User", DbType="VarChar(50)")]
		public string Address_User
		{
			get
			{
				return this._Address_User;
			}
			set
			{
				if ((this._Address_User != value))
				{
					this.OnAddress_UserChanging(value);
					this.SendPropertyChanging();
					this._Address_User = value;
					this.SendPropertyChanged("Address_User");
					this.OnAddress_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collar", DbType="Float")]
		public System.Nullable<double> collar
		{
			get
			{
				return this._collar;
			}
			set
			{
				if ((this._collar != value))
				{
					this.OncollarChanging(value);
					this.SendPropertyChanging();
					this._collar = value;
					this.SendPropertyChanged("collar");
					this.OncollarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chest", DbType="Float")]
		public System.Nullable<double> chest
		{
			get
			{
				return this._chest;
			}
			set
			{
				if ((this._chest != value))
				{
					this.OnchestChanging(value);
					this.SendPropertyChanging();
					this._chest = value;
					this.SendPropertyChanged("chest");
					this.OnchestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waist", DbType="Float")]
		public System.Nullable<double> waist
		{
			get
			{
				return this._waist;
			}
			set
			{
				if ((this._waist != value))
				{
					this.OnwaistChanging(value);
					this.SendPropertyChanging();
					this._waist = value;
					this.SendPropertyChanged("waist");
					this.OnwaistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hip", DbType="Float")]
		public System.Nullable<double> hip
		{
			get
			{
				return this._hip;
			}
			set
			{
				if ((this._hip != value))
				{
					this.OnhipChanging(value);
					this.SendPropertyChanging();
					this._hip = value;
					this.SendPropertyChanged("hip");
					this.OnhipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arm", DbType="Float")]
		public System.Nullable<double> arm
		{
			get
			{
				return this._arm;
			}
			set
			{
				if ((this._arm != value))
				{
					this.OnarmChanging(value);
					this.SendPropertyChanging();
					this._arm = value;
					this.SendPropertyChanged("arm");
					this.OnarmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sleeves", DbType="Float")]
		public System.Nullable<double> sleeves
		{
			get
			{
				return this._sleeves;
			}
			set
			{
				if ((this._sleeves != value))
				{
					this.OnsleevesChanging(value);
					this.SendPropertyChanging();
					this._sleeves = value;
					this.SendPropertyChanged("sleeves");
					this.OnsleevesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_back", DbType="Float")]
		public System.Nullable<double> back
		{
			get
			{
				return this._back;
			}
			set
			{
				if ((this._back != value))
				{
					this.OnbackChanging(value);
					this.SendPropertyChanging();
					this._back = value;
					this.SendPropertyChanged("back");
					this.OnbackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuffs", DbType="Float")]
		public System.Nullable<double> cuffs
		{
			get
			{
				return this._cuffs;
			}
			set
			{
				if ((this._cuffs != value))
				{
					this.OncuffsChanging(value);
					this.SendPropertyChanging();
					this._cuffs = value;
					this.SendPropertyChanged("cuffs");
					this.OncuffsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lengths", DbType="Float")]
		public System.Nullable<double> lengths
		{
			get
			{
				return this._lengths;
			}
			set
			{
				if ((this._lengths != value))
				{
					this.OnlengthsChanging(value);
					this.SendPropertyChanging();
					this._lengths = value;
					this.SendPropertyChanged("lengths");
					this.OnlengthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yore", DbType="Float")]
		public System.Nullable<double> yore
		{
			get
			{
				return this._yore;
			}
			set
			{
				if ((this._yore != value))
				{
					this.OnyoreChanging(value);
					this.SendPropertyChanging();
					this._yore = value;
					this.SendPropertyChanged("yore");
					this.OnyoreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
